export const defaultSettings = {
  PTT: true,
  setBadge: true,
  streamPreview: true,
  fakePreview: "",
  noAFK: true,
  spotifyPremium: true,
  spotifyPause: true,
  maxAccounts: true,
  clientThemes: true,
  gradientPreset: null,
  plainFolderIcon: true,
  favIMG: true,
  ringtone: "call_ringing_beat.mp3",
  spam: true,
  voiceMessage: true,
};
